language: java

jdk: oraclejdk8

services:
  - docker

dist: trusty

script:
  - cd eureka-server-demo
  - docker-compose build
  - docker tag shubhamtricon/discovery-server-image:latest shubhamtricon/ecommerce-discovery-server:1.0
  - docker push shubhamtricon/ecommerce-discovery-server:1.0
  - docker rmi shubhamtricon/discovery-server-image:latest -f
  - docker pull shubhamtricon/ecommerce-discovery-server:latest
  - docker run shubhamtricon/discovery-server-image:latest

cache:
  directories:
    - $HOME/.m2

deploy:
  provider: Heroku
  api_key:
    secure: 4a378af3-5aca-4765-a4e2-969d3059685e
  app: demo-app-97
  skip_cleanup: true
